### ISSUE TITLE
Difference btw these 2 codes?

### ISSUE THREAD

**Issue by sherigr** [sherigr/ForeScore#1]
@harimohanraj89 @htella @DrRobotmck

For user authentication, is there a main difference between the code we used in our program:
def current_user
  User.find(session[:current_user_id]) if session[:current_user_id] 
end

And the way it's written in Rails Guide:
def current_user
    @_current_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end

Looks to me to be the same just our in-class way of writing is "easier".

Thanks

**Comment by harimohanraj89** [comment]
The Rails Guide code is a little more robust (doesn't break as easily in weird cases), but you apart from that, same thing. You can go ahead and use our code. It is simpler to implement.
