### ISSUE TITLE
Scorecard not working after adding total_score

### ISSUE THREAD

**Issue by sherigr** [sherigr/ForeScore#3]
@harimohanraj89 @htella @DrRobotmck 

The addition of total_score method in model, controller and editing views/form, new & show worked (in the console & on website scorecard) when I first made the changes last night. After I added the similar changes for Par scorecard new, edit, show all broke. Now much of what was working with scorecard is not. 

Can use some assistance to help understand why it's not working. Currently getting error "+"  not defined

**Comment by htella** [comment]
let me see what I can do

**Comment by sherigr** [comment]
Thanks Harish.

I just committed another update. I got the new & edit to work however, when it goes to show it’s still not.
And I didn’t even check yet to see if it’s working in console. Just that I was able to get beyond Active Record Error Message via site.

**Comment by htella** [comment]
Hmm before getting to your show page I see something that could use fixing in your `Scorecard` model. 

You have class methods going on for `self.total_score` and `self.total_par`. I see before you had these as instance methods. Just `total_score` and `total_par`.  They make more sense as instance methods because they are operating an a particular instance of the scorecard. Is there a reason you change them. Was there an error you were getting when they were instance methods.

**Comment by sherigr** [comment]
I was originally using the instance methods. When I added .self to each of the holes it was working. Then all of a sudden it stopped working so I then kept trying to change things around. With one of the errors, I can’t recall on which method, I was even getting + is undefined. The + being in between each of the holes.

Truthfully, getting so frustrated I just kept trying to refactor hoping something would work.

**Comment by htella** [comment]
Hmm have you tried this. Creating a new instance of your scorecard on the Rails console. Then with your new instance calling the `total_score` and `total_par` methods on it. It won't work I believe. Because they are not instance methods. 

Let me show you some sample code.

**Comment by sherigr** [comment]
Last night, I had done that in Rails console, calling on a scorecard and then total_score and it worked (using the first method on the model page). I then tried it via the website, updating and existing form, and it also worked. It seems as though once I added total_par it all broke and then I haven’t been able to fix.

Doesn’t work in console. using the original method of (self.hole1 + self.hole2……) this is the error message I’m now getting. Which is different from the past error messages.

**Comment by htella** [comment]
this is what I talking about 

``` ruby
sc = Scorecard.new
sc.hole1 = 3
sc.hole2 = 9
sc.save

# then I try 
sc.total_score 

# I get an error saying method undefined, because you made it a Class method and not an Instance method
```

**Comment by htella** [comment]
If I make `total_score` or `total_par` instance methods and try to call them like in the above example I will get this result 

``` ruby
sc = Scorecard.new
sc.hole1 = 3
sc.hole2 = 9
sc.save

# then I try 
sc.total_score 
# I get this error TypeError: nil can't be coerced into Fixnum
```

This happened because I didn't set a number value to all of the holes. I only did it for hole1 and hole2.

**Comment by htella** [comment]
Sheri, I didn't see an error message in your last post can you send it again.

**Comment by sherigr** [comment]
Sorry, not sure if I’m fully understanding. So in the model I need to make it an Instance method? I originally had put self.total_score, I thought that would make it instance? 

I was actually thinking of reverting it all back to the code from yesterday afternoon when all was working before I started playing with total score & par. And trying to start over. But since the changes touch upon a bunch of files, wasn’t sure if I can revert it or do I need to copy and paste from github?

Is it possible for us to chat on the phone?

**Comment by htella** [comment]
And I took a look, there shouldn't be any difference between how `total_score` and `total_par` work unless I missing something.

**Comment by sherigr** [comment]
Just resent to your email address

**Comment by sherigr** [comment]
Exactly what I thought, which was why once total score appeared to be working I then created total par. That’s when I started getting the errors.

This is the error I got once I added total Par.

**Comment by htella** [comment]
Ah probably just that you didn't set values for par for all the holes. 

As far as reverting you code, let's try to do it manually. I don't think there will be much that need to change.

**Comment by htella** [comment]
Make `total_score` and `total_par` instance methods. And let me know what you get.

**Comment by htella** [comment]
And instance methods are the ones without self in the method name.

**Comment by htella** [comment]
exactly like you have the first two commented out methods here https://github.com/sherigr/ForeScore/blob/edits/app/models/scorecard.rb

**Comment by htella** [comment]
By the way, the pictures you set me are helpful, but they are really low resolution. I can't make much out. If you have other errors please make them bigger picture.s

**Comment by sherigr** [comment]
That’s what I had used when I tested in console a few mins ago. That’s when I received the error message I sent, regarding undefined method/local variable for hole1

**Comment by htella** [comment]
can you push what you have, should I be looking at the edits branch?

**Comment by sherigr** [comment]
Hmm, those were screen grabs.Will try to make bigger

**Comment by sherigr** [comment]
just pushed most recent version I’m working with.

Yes, edits branch

**Comment by htella** [comment]
ok taking a look

**Comment by htella** [comment]
just tried you code. total_score and total_par are working for me when I set values for all the hole's score and par values

``` ruby
sc = Scorecard.new
sc.par1 = 9 
sc.par2 = 9
sc.par3 = 9
sc.par4 = 9
sc.par5 = 9
sc.par6 = 9
sc.par7 = 9
sc.par8 = 9
sc.par9 = 9
sc.par10 = 9
sc.par11 = 9
sc.par12 = 9
sc.par13 = 9
sc.par14 = 9
sc.par15 = 9
sc.par16 = 9
sc.par17 = 9
sc.par18 = 9

sc.hole1 = 9
sc.hole2 = 9
sc.hole3 = 9
sc.hole4 = 9
sc.hole5 = 9
sc.hole6 = 9
sc.hole7 = 9
sc.hole8 = 9
sc.hole9 = 9
sc.hole10 = 9
sc.hole11 = 9
sc.hole12 = 9
sc.hole13 = 9
sc.hole14 = 9
sc.hole15 = 9
sc.hole16 = 9
sc.hole17 = 9
sc.hole18 = 9
sc.save

# then I try 
sc.total_par
sc.total_score 
```

**Comment by htella** [comment]
If there is even one score or par value missing though, `total_par` and `total_score` will break.

**Comment by htella** [comment]
If this works fine for you and you are getting an error elsewhere related to this change, let me know.

**Comment by sherigr** [comment]
Using the code I sent you, if I try to edit in via the site, I get active record error.
Example, I went to /scorecard/19/edit and receive this message
Says: Showing /Users/sgrossman00/Repos/fore_score_app/app/views/scorecards/show.html.erb where line #88 raised:
nil can't be coerced into Fixnum

**Comment by sherigr** [comment]
How do I set it so nil doesn’t break it? I feel like someplace in need to add nil? but not sure where

**Comment by htella** [comment]
Hmm let me see

**Comment by sherigr** [comment]
Also, in console I can see, if I pull up last scorecard, it shows me id 21 and I can see hole 18 nil. So when I go onto site and show that scorecard it has a value in hole 18. When I hit “update”, I get the error message I just sent you. So it’s not updating so that it stays in the database nor is the redirect of that working

**Comment by htella** [comment]
I'm not sure about you last comment. But this will definately help you out. 

Get rid of the following section towards the bottom of your _form.html.erb

``` html
    <div class="total-score">   
    <div id="all-holes">
        <%= f.label :total  %><br>
        <%= f.text_field :total_score %><br>
        <%= f.label :Par %><br>
        <%= f.text_field :total_par %><br>
        </div>
    </div>
```

The user never needs to specify total_score or total_par. You have added those instance methods so they are calculated automatically.

**Comment by sherigr** [comment]
OK, will try that. By eliminating this, where am I telling the program to create/show a total score/par box?

**Comment by htella** [comment]
The user should see info on the total_score and total_par when they visit the scorecard show page. Or at least this is how I am envisioning it. 

As for as the par value for hole 18 not getting set. Take a look at this section from your _form.html.erb

``` html
    <div id="hole-18">
        <%= f.label :hole_18  %><br>
        <%= f.text_field :hole18 %><br>
        <%= f.label :par_18 %><br>
        <%= f.text_field :par8 %><br>
        <div>
        </div>
```

on the last text_field line, it should be `f.text_field :par18` not  `f.text_field :par8`

**Comment by sherigr** [comment]
Deleted that and tried again, getting error message: Showing /Users/sgrossman00/Repos/fore_score_app/app/views/scorecards/show.html.erb where line #88 raised:
nil can't be coerced into Fixnum
I’m realizing that “nil” can’t be in scorecard or it causes it to break. So went into Rails console so I can find a card id number that has completed scorecard. I’m noticing that cards that were completed, for some reason are showing nil for hole 18. So that’s probably one of the problems right there. However, when I open up that same scorecard via the website, it does show a value for hole 18. And if I just hit update I then go to that error message.

**Comment by sherigr** [comment]
Aargh, sorry about that. Just fixed. Now I know why the scorecards had nil for hole 18. 

But fixing this still isn’t resolving if I try to update a card or “show"

**Comment by htella** [comment]
Does your show page work for a Scorecard that has values for all the holes and all the par values?

**Comment by htella** [comment]
Also should your show page be rendering a form or should it just output information based on the data in the Scorecard model? I believe you have the second in your show page, but you have it commented out.

**Comment by sherigr** [comment]
I can open Scorecard form /scorecards page and it will show the entire form & values. But once I hit update, it takes me back to the “error"

**Comment by sherigr** [comment]
The show page should display the entire form. Not sure why commented out but just removed comments.

Still getting:
TypeError in Scorecards#show
Showing /Users/sgrossman00/Repos/fore_score_app/app/views/scorecards/show.html.erb where line #88 raised:

nil can't be coerced into Fixnum
Extracted source (around line #15):
13
14
15
16
17
18

```
    total_par = (self.par1 + self.par2 + self.par3 + self.par4 + self.par5 + self.par6 + 
    self.par7 + self.par8 + self.par9 + self.par10 + self.par11 + self.par12 + self.par13 +
    self.par14 + self.par15 + self.par16 + self.par17 + self.par18)
end
```

# def total_score

**Comment by sherigr** [comment]
just pushed the current version of what I’m working with

For some reason they wouldn’t add with git add . so copied each to add and pushed

**Comment by htella** [comment]
Hmm my hunch is that you are trying to look at the show page for a Scorecard with some value not defined. Can you pull up the same Scorecard in the rails console and check that it has values for everything.

Also I think you scorecard shouldn't show the form. It should only output the data from the Scorecard.

as in this line should not be present in your show.html.erb

`<%= render 'form'  %>`

**Comment by htella** [comment]
Sorry, I meant to write above that you scorecard show page shouldn't show the form.

**Comment by htella** [comment]
can you confirm that this Scorecard has values for all the holes in the rails console? Grab the same Scorecard by using the id.

**Comment by sherigr** [comment]
Yes, in the Rails console, if I do Scoredcard.find(16) it displays that scorecard.

I put the render form in yesterday b/c I did not like how it was showing the info for a scorecard. I prefer for it to show the scorecard the same as when it’s created. That said, I still want to try to style scorecards but haven’t had a chance to do any styling yet.

**Comment by sherigr** [comment]
I’m going to have to create new scorecard and then pull that since that error I had on hole18 has caused all scorecards to be nil. If it works, then I guess I’ll know the reason it’s been breaking is due to hole18 being nil.

**Comment by sherigr** [comment]
Creating new scorecard via the website (/scorecards/new). Once I hit submit, it’s showing the info but not on the form as it had been (or how I’d like it to appear). Also, it’s not totaling score or par, those are showing as nil.

If I go to that scorecard: /scorecard/22/edit and then hit update form it does take me back to the scorecard form so at least that tells me the other kept breaking b/c of nil. 

However, it’s now showing the values of the holes/pars in the form BUT also in a line below the form, which is actually where the total score & par is appearing.

Scorecard
1/27/15
morning joe

Date

Course played

Hole 1

Par 1

Hole 2

Par 2

Hole 3

Par 3

Hole 4

Par 4

Hole 5

Par 5

Hole 6

Par 6

Hole 7

Par 7

Hole 8

Par 8

Hole 9

Par 9

Hole 10

Par 10

Hole 11

Par 11

Hole 12

Par 12

Hole 13

Par 13

Hole 14

Par 14

Hole 15

Par 15

Hole 16

Par 16

Hole 17

Par 17

Hole 18

Par 18

5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
5
4
90
72

Edit Back Home

**Comment by htella** [comment]
Ok 2 separate things here.

Why does submitting a new Scorecard just show you a bunch of JSON. Because that's what the controller action is telling it to do. Check it out.

``` ruby
  def create
    @scorecard = Scorecard.create(scorecard_params)
    render json: @scorecard
  end
```

it looks like you also have some commented out code above that would redirect to the show page. That would definitely do the trick. Here it is again. Withou the user authorization line. 

``` ruby
def create
  @scorecard = Scorecard.new(scorecard_params)
  if @scorecard.save
    redirect_to @scorecard
  else
    render :new
  end
end
```

**Comment by htella** [comment]
As for why `total_score` and `total_par` show up as nil. This is because those fields in the database are nil. We don't really need those fields in our database at all.

The reason why `total_score` and `total_par` show up on your show.html.erb page is because the code there calls the `.total_score` and `.total_par` instance methods on the Scorecard instance. This calculates the total_score and total_par using the other fields from the db. (par1, par2, par3, ... etc)
